/**
 * This library can throw a variety of error objects, descriptive of different
 * circumstances, to allow callers to wrap error handling in translation systems.
 *
 * The most actionable / specific errors get wrapped in specific classes, but some
 * still carry generic untranslatable strings.
 */

/**
 * Base class; handles converting errors to JSON blobs and back again.
 */
class CriticalCssError extends Error {
	constructor( type, data, children ) {
		if ( ! CriticalCssErrorTypes[ type ] ) {
			type = 'UnknownError';
			data = { message: JSON.stringify( data ) };
		}

		super( CriticalCssErrorTypes[ type ].getMessage( data, children ) );

		this.type = type;
		this.data = data;
		this.children = children || [];
	}

	/**
	 * Returns children of this error (if any).
	 */
	getChildren() {
		return this.children;
	}

	/**
	 * Returns the type of error as a string.
	 */
	getType() {
		return this.type;
	}

	/**
	 * Returns the error data.
	 */
	getData() {
		return this.data;
	}

	/**
	 * Returns true if this error object has the specified data value.
	 *
	 * @param {string} key
	 */
	has( key ) {
		return Object.prototype.hasOwnProperty.call( this.data, key );
	}

	/**
	 * Gets the data value with the specified key, or undefined if not defined.
	 *
	 * @param {string} key
	 */
	get( key ) {
		return this.data[ key ];
	}

	/**
	 * Standard JSON serialization endpoint; returns a JSON
	 * friendly object.
	 */
	toJSON() {
		const typeClass = CriticalCssErrorTypes[ this.type ];

		return {
			type: this.type,
			data: this.data,
			message: typeClass.getMessage( this.data, this.children ),
			children: this.children.map( ( child ) => child.toJSON() ),
		};
	}

	/**
	 * Reverse of toJSON; constructs a CriticalCssError object from
	 * a previously serialized value.
	 *
	 * @param {Object} jsonObject - JSON compatible object
	 */
	static fromJSON( jsonObject ) {
		const ErrorClass = CriticalCssErrorTypes[ jsonObject.type ];
		if ( ! ErrorClass ) {
			return new UnknownError( {
				message: jsonObject.message || jsonObject,
			} );
		}

		const rawChildren = jsonObject.children || [];
		const children = rawChildren.map( CriticalCssError.fromJSON );

		return new ErrorClass( jsonObject.data, children );
	}
}

/**
 * UnknownError - Used for any unrecognized error.
 */
class UnknownError extends CriticalCssError {
	constructor( { message } ) {
		super( 'UnknownError', { message } );
	}

	static getMessage( data ) {
		return data.message;
	}
}

/**
 * HttpError - Indicates an HTTP request has failed with a non-2xx status code.
 */
class HttpError extends CriticalCssError {
	constructor( { url, code } ) {
		super( 'HttpError', { url, code } );
	}

	static getMessage( data ) {
		return `HTTP error ${ data.code } on URL ${ data.url }`;
	}
}

/**
 * GenericUrlError - Indicates that fetch() threw an error with its own error string.
 * Contains a raw (and difficult to translate) error message generated by fetch.
 */
class GenericUrlError extends CriticalCssError {
	constructor( { url, message } ) {
		super( 'GenericUrlError', { url, message } );
	}

	static getMessage( data ) {
		return `Error while loading ${ data.url }: ${ data.message }`;
	}
}

/**
 * CrossDomainError - Indicates that a requested URL failed due to CORS / security
 * limitations imposed by the browser.
 */
class CrossDomainError extends CriticalCssError {
	constructor( { url } ) {
		super( 'CrossDomainError', { url } );
	}

	static getMessage( data ) {
		return `Failed to fetch cross-domain content at ${ data.url }`;
	}
}

/**
 * LoadTimeoutError - Indicates that an HTTP request failed due to a timeout.
 */
class LoadTimeoutError extends CriticalCssError {
	constructor( { url } ) {
		super( 'LoadTimeoutError', { url } );
	}

	static getMessage( data ) {
		return `Timeout while reading ${ data.url }`;
	}
}

/**
 * RedirectError - Indicates that a requested URL failed due to an HTTP redirection of that url.
 */
class RedirectError extends CriticalCssError {
	constructor( { url, redirectUrl } ) {
		super( 'RedirectError', { url, redirectUrl } );
	}

	static getMessage( data ) {
		return `Failed to process ${ data.url } because it redirects to ${ data.redirectUrl } which cannot be verified`;
	}
}

/**
 * UrlVerifyError - Indicates that a provided BrowserInterface verifyUrl
 * callback returned false for a page which was otherwise loaded successfully.
 */
class UrlVerifyError extends CriticalCssError {
	constructor( { url } ) {
		super( 'UrlVerifyError', { url } );
	}

	static getMessage( data ) {
		return `Failed to verify page at ${ data.url }`;
	}
}

/**
 * ConfigurationError - Indicates that this library was called with invalid
 * parameters.
 */
class ConfigurationError extends CriticalCssError {
	constructor( { message } ) {
		super( 'ConfigurationError', { message } );
	}

	static getMessage( data ) {
		return `Invalid configuration: ${ data.message }`;
	}
}

/**
 * InternalError - Indicates something went wrong in the guts of this library,
 * and probably represent a bug that needs to be fixed.
 */
class InternalError extends CriticalCssError {
	constructor( { message } ) {
		super( 'InternalError', { message } );
	}

	static getMessage( data ) {
		return `Internal error: ${ data.message }`;
	}
}

/**
 * SuccessTargetError - Indicates that insufficient pages loaded to meet
 * a specified success target.
 */
class SuccessTargetError extends CriticalCssError {
	constructor( data, children ) {
		super( 'SuccessTargetError', data, children );
	}

	static getMessage( data, children ) {
		return (
			'Insufficient pages loaded to meet success target. Errors:\n' +
			children.map( ( error ) => error.message ).join( '\n' )
		);
	}
}

/**
 * NoCSSError - Indicates the url looked at did not have any CSS.
 */
class NoCSSError extends CriticalCssError {
	constructor( { url } ) {
		super( 'NoCSSError', { url } );
	}

	static getMessage( data ) {
		return `The ${ data.url } url does not seem to have any CSS`;
	}
}

const CriticalCssErrorTypes = {
	// Detailed errors
	CrossDomainError,
	LoadTimeoutError,
	RedirectError,
	HttpError,
	UrlVerifyError,
	SuccessTargetError,
	NoCSSError,

	// Unspecific errors
	GenericUrlError,

	// Usage / internal errors
	ConfigurationError,
	InternalError,

	// External errors / unknown origin.
	UnknownError,
};

module.exports = {
	...CriticalCssErrorTypes,
	CriticalCssError,
};
