name: Add issues to Project Board

on:
  issues:
    types: [opened, edited, reopened, labeled]

jobs:
  insert:
    runs-on: ubuntu-latest

    steps:
      - uses: leonsteinhaeuser/project-beta-automations@939000fb1900c9fc4f7b5058a09d9f833ebc6859 # v2.2.1
        with:
          gh_token: ${{ secrets.PROJECT_MANAGEMENT_TOKEN }}
          organization: "automattic"
          project_id: 322
          resource_node_id: ${{ github.event.issue.node_id }}
