name: Jest Tests
on: [push]
jobs:
  jest-tests:
    runs-on: ubuntu-18.04
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test
