name: Code Lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint
